[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.52.3", features = ["sync", "rt", "macros"] }
axum = {  version = "0.7", features = ["ws"] }
tower-http = { version = "0.5", features = ["fs", "cors"] }
rust-embed = "8.12.0"
mime_guess = "2.0.5"
serde = { workspace = true, features = ["derive"] }
talos-auth = { path = "../auth", package = "auth" }
talos-core = { path = "../core", package = "core" }
serde_json = "1.0.150"
rdev = { version = "0.5.3", features = ["unstable_grab"] }
notify-rust = "4.18.0"
app_dirs2 = "2.5.5"