[package]
name = "ai"
version = "0.1.0"
edition = "2024"

[dependencies]
talos-core = { path = "../core", package = "core" }
tokio = { workspace = true }
serde = { workspace = true }
portable-pty = "0.8"
strip-ansi-escapes = "0.2"
gemini-live = "0.1.8"
reqwest = { version = "0.13.4", features = ["json"] }
oauth2 = "5.0.0"
magic-crypt = "4.0.1"
