[package]
name = "ai"
version = "0.1.0"
edition = "2024"

[dependencies]
talos-core = { path = "../core", package = "core" }
executor = { path = "../executor" }
tokio = { workspace = true }
serde_json = { workspace = true }
portable-pty = "0.9.0"
strip-ansi-escapes = "0.2"
gemini-live = "0.1.8"
rodio = "0.22.2"
app_dirs2 = "2.5.5"
mistralrs = "0.8.1"
turso = "0.8.0-pre.1"
fastembed = "5.17.3"