[package]
name = "ai"
version = "0.1.0"
edition = "2024"

[dependencies]
talos-core = { path = "../core", package = "core" }
executor = { path = "../executor", package = "executor" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
portable-pty = "0.8"
strip-ansi-escapes = "0.2"
gemini-live = "0.1.8"
reqwest = { version = "0.13.4", features = ["json", "form"] }
oauth2 = "5.0.0"
magic-crypt = "4.0.1"
rodio = "0.22.2"
ratatui = "0.30.2"
tui-prompts = "0.6.7"
crossterm = "0.29.0"
rust-mcp-sdk = "0.10.0"
ui = { path = "../ui", package = "ui" }
async-trait = "0.1.89"
# TODO: Add mcp dependencies here