[package]
name = "talos"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
talos-core = { path = "../core", package = "talos_core" }
talos-audio = { path = "../audio", package = "audio" }
talos-auth = { path = "../auth", package = "auth" }
talos-ai = { path = "../ai", package = "ai" }
talos-executor = { path = "../executor", package = "executor" }
talos-ui = { path = "../ui", package = "ui" }
talos-transport = { path = "../transport", package = "transport" }
talos-plugins = { path = "../plugins", package = "plugins"}
app_dirs2 = "2.5.5"
notify-rust = "4.18.0"
any-tts = "0.1.2"
dirs = "6.0.0"
auto-launch = "0.6.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["wincon", "winuser"] }