[package]
name = "executor"
version = "0.1.0"
edition = "2024"

[dependencies]
talos-core = { path = "../core", package = "core" }
tokio = { workspace = true }
xcap = "0.9.6"
image = "0.25.10"
enigo = "0.6.1"
serde_json = "1.0.150"
mcpkit = "0.6.0"
mcpkit-axum = "0.6.0"
axum = "0.8.9"
async-trait = "0.1.89"
mcpkit-server = "0.6.0"
mcpkit-core = "0.6.0"