import { Button, VerticalBox, LineEdit, ListView, HorizontalBox } from "std-widgets.slint";

export struct LogEntry {
    sender: string,
    message: string,
}

export component AppWindow inherits Window {
    in-out property <bool> mode;
    in-out property <bool> show_mode: true;
    in-out property <bool> api_completed;
    
    in-out property <[LogEntry]> user_logs;
    in-out property <[LogEntry]> api_logs;

    callback send_signin();
    callback send_mode(bool);
    callback send_api(string);

    if (show_mode):
        VerticalBox {
            Button {
                text: "Application Programming Interface (API)";
                clicked => {
                    mode = false;
                    send_mode(mode);
                    show_mode = false;
                }
            }
            Button {
                text: "Google Cloud Platform (GCP)";
                clicked => {
                    mode = true;
                    send_mode(mode);
                    show_mode = false;
                }
            }
        }
    if (!show_mode && mode):
        VerticalBox {
            Button {
                text: "Back";
                clicked => {
                    show_mode = true;
                }
            }
            Button {
                text: "Sign-In";
                clicked => {
                    send_signin();
                }
            }
        }
    if (!show_mode && !mode && !api_completed):
        VerticalBox {
            Button {
                text: "Back";
                clicked => {
                    show_mode = true;
                }
            }
            api:= LineEdit {
                placeholder-text: "API Key";
                accepted(text) => {
                    send_api(text);
                }
            }
            Button {
                text: "Submit";
                clicked => {
                    api_completed = true;
                    send_api(api.text);
                }
            }
        }
    if (!show_mode && !mode && api_completed):
        HorizontalBox {
            ListView {
                for log in root.user_logs: Text {
                    text: log.sender + ": " + log.message;
                }
            }
            ListView {
                for log in root.api_logs: Text {
                    text: log.sender + ": " + log.message;
                }
            }
        }
}